/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface MultiversePredictionInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "BASIS_POINTS"
      | "LIQUIDATION_THRESHOLD"
      | "MAX_LEVERAGE_BPS"
      | "MIN_COLLATERAL_RATIO"
      | "children"
      | "claim"
      | "collateralToken"
      | "createChildPrediction"
      | "createRootPrediction"
      | "getChainHealth"
      | "getChildren"
      | "getUserPredictions"
      | "owner"
      | "predictionIdCounter"
      | "predictions"
      | "renounceOwnership"
      | "resolvePrediction"
      | "transferOwnership"
      | "userPredictions"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "CollateralLocked"
      | "Liquidation"
      | "LoanIssued"
      | "OwnershipTransferred"
      | "PredictionCreated"
      | "PredictionResolved"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "BASIS_POINTS",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "LIQUIDATION_THRESHOLD",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "MAX_LEVERAGE_BPS",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "MIN_COLLATERAL_RATIO",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "children",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "claim", values: [BigNumberish]): string;
  encodeFunctionData(
    functionFragment: "collateralToken",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "createChildPrediction",
    values: [
      BigNumberish,
      AddressLike,
      BigNumberish,
      BigNumberish,
      BigNumberish
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "createRootPrediction",
    values: [AddressLike, BigNumberish, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getChainHealth",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getChildren",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getUserPredictions",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "predictionIdCounter",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "predictions",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "resolvePrediction",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "userPredictions",
    values: [AddressLike, BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "BASIS_POINTS",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "LIQUIDATION_THRESHOLD",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "MAX_LEVERAGE_BPS",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "MIN_COLLATERAL_RATIO",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "children", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "claim", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "collateralToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createChildPrediction",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createRootPrediction",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getChainHealth",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getChildren",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getUserPredictions",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "predictionIdCounter",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "predictions",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "resolvePrediction",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "userPredictions",
    data: BytesLike
  ): Result;
}

export namespace CollateralLockedEvent {
  export type InputTuple = [predictionId: BigNumberish, amount: BigNumberish];
  export type OutputTuple = [predictionId: bigint, amount: bigint];
  export interface OutputObject {
    predictionId: bigint;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace LiquidationEvent {
  export type InputTuple = [
    predictionId: BigNumberish,
    liquidator: AddressLike
  ];
  export type OutputTuple = [predictionId: bigint, liquidator: string];
  export interface OutputObject {
    predictionId: bigint;
    liquidator: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace LoanIssuedEvent {
  export type InputTuple = [predictionId: BigNumberish, amount: BigNumberish];
  export type OutputTuple = [predictionId: bigint, amount: bigint];
  export interface OutputObject {
    predictionId: bigint;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PredictionCreatedEvent {
  export type InputTuple = [
    predictionId: BigNumberish,
    creator: AddressLike,
    parentId: BigNumberish,
    collateral: BigNumberish,
    loan: BigNumberish
  ];
  export type OutputTuple = [
    predictionId: bigint,
    creator: string,
    parentId: bigint,
    collateral: bigint,
    loan: bigint
  ];
  export interface OutputObject {
    predictionId: bigint;
    creator: string;
    parentId: bigint;
    collateral: bigint;
    loan: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PredictionResolvedEvent {
  export type InputTuple = [predictionId: BigNumberish, outcome: boolean];
  export type OutputTuple = [predictionId: bigint, outcome: boolean];
  export interface OutputObject {
    predictionId: bigint;
    outcome: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface MultiversePrediction extends BaseContract {
  connect(runner?: ContractRunner | null): MultiversePrediction;
  waitForDeployment(): Promise<this>;

  interface: MultiversePredictionInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  BASIS_POINTS: TypedContractMethod<[], [bigint], "view">;

  LIQUIDATION_THRESHOLD: TypedContractMethod<[], [bigint], "view">;

  MAX_LEVERAGE_BPS: TypedContractMethod<[], [bigint], "view">;

  MIN_COLLATERAL_RATIO: TypedContractMethod<[], [bigint], "view">;

  children: TypedContractMethod<
    [arg0: BigNumberish, arg1: BigNumberish],
    [bigint],
    "view"
  >;

  claim: TypedContractMethod<
    [predictionId: BigNumberish],
    [void],
    "nonpayable"
  >;

  collateralToken: TypedContractMethod<[], [string], "view">;

  createChildPrediction: TypedContractMethod<
    [
      parentId: BigNumberish,
      priceFeed: AddressLike,
      priceTarget: BigNumberish,
      deadline: BigNumberish,
      leverageBPS: BigNumberish
    ],
    [bigint],
    "nonpayable"
  >;

  createRootPrediction: TypedContractMethod<
    [
      priceFeed: AddressLike,
      priceTarget: BigNumberish,
      deadline: BigNumberish,
      leverageBPS: BigNumberish
    ],
    [bigint],
    "payable"
  >;

  getChainHealth: TypedContractMethod<
    [predictionId: BigNumberish],
    [[boolean, bigint] & { healthy: boolean; ratio: bigint }],
    "view"
  >;

  getChildren: TypedContractMethod<
    [parentId: BigNumberish],
    [bigint[]],
    "view"
  >;

  getUserPredictions: TypedContractMethod<
    [user: AddressLike],
    [bigint[]],
    "view"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  predictionIdCounter: TypedContractMethod<[], [bigint], "view">;

  predictions: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        bigint,
        string,
        bigint,
        bigint,
        bigint,
        string,
        bigint,
        bigint,
        boolean,
        boolean,
        bigint,
        boolean
      ] & {
        id: bigint;
        creator: string;
        parentId: bigint;
        collateralAmount: bigint;
        loanAmount: bigint;
        priceFeed: string;
        priceTarget: bigint;
        deadline: bigint;
        resolved: boolean;
        outcome: boolean;
        collateralizationRatio: bigint;
        liquidated: boolean;
      }
    ],
    "view"
  >;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  resolvePrediction: TypedContractMethod<
    [predictionId: BigNumberish],
    [void],
    "nonpayable"
  >;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  userPredictions: TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [bigint],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "BASIS_POINTS"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "LIQUIDATION_THRESHOLD"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "MAX_LEVERAGE_BPS"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "MIN_COLLATERAL_RATIO"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "children"
  ): TypedContractMethod<
    [arg0: BigNumberish, arg1: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "claim"
  ): TypedContractMethod<[predictionId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "collateralToken"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "createChildPrediction"
  ): TypedContractMethod<
    [
      parentId: BigNumberish,
      priceFeed: AddressLike,
      priceTarget: BigNumberish,
      deadline: BigNumberish,
      leverageBPS: BigNumberish
    ],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "createRootPrediction"
  ): TypedContractMethod<
    [
      priceFeed: AddressLike,
      priceTarget: BigNumberish,
      deadline: BigNumberish,
      leverageBPS: BigNumberish
    ],
    [bigint],
    "payable"
  >;
  getFunction(
    nameOrSignature: "getChainHealth"
  ): TypedContractMethod<
    [predictionId: BigNumberish],
    [[boolean, bigint] & { healthy: boolean; ratio: bigint }],
    "view"
  >;
  getFunction(
    nameOrSignature: "getChildren"
  ): TypedContractMethod<[parentId: BigNumberish], [bigint[]], "view">;
  getFunction(
    nameOrSignature: "getUserPredictions"
  ): TypedContractMethod<[user: AddressLike], [bigint[]], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "predictionIdCounter"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "predictions"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        bigint,
        string,
        bigint,
        bigint,
        bigint,
        string,
        bigint,
        bigint,
        boolean,
        boolean,
        bigint,
        boolean
      ] & {
        id: bigint;
        creator: string;
        parentId: bigint;
        collateralAmount: bigint;
        loanAmount: bigint;
        priceFeed: string;
        priceTarget: bigint;
        deadline: bigint;
        resolved: boolean;
        outcome: boolean;
        collateralizationRatio: bigint;
        liquidated: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "resolvePrediction"
  ): TypedContractMethod<[predictionId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "userPredictions"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [bigint],
    "view"
  >;

  getEvent(
    key: "CollateralLocked"
  ): TypedContractEvent<
    CollateralLockedEvent.InputTuple,
    CollateralLockedEvent.OutputTuple,
    CollateralLockedEvent.OutputObject
  >;
  getEvent(
    key: "Liquidation"
  ): TypedContractEvent<
    LiquidationEvent.InputTuple,
    LiquidationEvent.OutputTuple,
    LiquidationEvent.OutputObject
  >;
  getEvent(
    key: "LoanIssued"
  ): TypedContractEvent<
    LoanIssuedEvent.InputTuple,
    LoanIssuedEvent.OutputTuple,
    LoanIssuedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "PredictionCreated"
  ): TypedContractEvent<
    PredictionCreatedEvent.InputTuple,
    PredictionCreatedEvent.OutputTuple,
    PredictionCreatedEvent.OutputObject
  >;
  getEvent(
    key: "PredictionResolved"
  ): TypedContractEvent<
    PredictionResolvedEvent.InputTuple,
    PredictionResolvedEvent.OutputTuple,
    PredictionResolvedEvent.OutputObject
  >;

  filters: {
    "CollateralLocked(uint256,uint256)": TypedContractEvent<
      CollateralLockedEvent.InputTuple,
      CollateralLockedEvent.OutputTuple,
      CollateralLockedEvent.OutputObject
    >;
    CollateralLocked: TypedContractEvent<
      CollateralLockedEvent.InputTuple,
      CollateralLockedEvent.OutputTuple,
      CollateralLockedEvent.OutputObject
    >;

    "Liquidation(uint256,address)": TypedContractEvent<
      LiquidationEvent.InputTuple,
      LiquidationEvent.OutputTuple,
      LiquidationEvent.OutputObject
    >;
    Liquidation: TypedContractEvent<
      LiquidationEvent.InputTuple,
      LiquidationEvent.OutputTuple,
      LiquidationEvent.OutputObject
    >;

    "LoanIssued(uint256,uint256)": TypedContractEvent<
      LoanIssuedEvent.InputTuple,
      LoanIssuedEvent.OutputTuple,
      LoanIssuedEvent.OutputObject
    >;
    LoanIssued: TypedContractEvent<
      LoanIssuedEvent.InputTuple,
      LoanIssuedEvent.OutputTuple,
      LoanIssuedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "PredictionCreated(uint256,address,uint256,uint256,uint256)": TypedContractEvent<
      PredictionCreatedEvent.InputTuple,
      PredictionCreatedEvent.OutputTuple,
      PredictionCreatedEvent.OutputObject
    >;
    PredictionCreated: TypedContractEvent<
      PredictionCreatedEvent.InputTuple,
      PredictionCreatedEvent.OutputTuple,
      PredictionCreatedEvent.OutputObject
    >;

    "PredictionResolved(uint256,bool)": TypedContractEvent<
      PredictionResolvedEvent.InputTuple,
      PredictionResolvedEvent.OutputTuple,
      PredictionResolvedEvent.OutputObject
    >;
    PredictionResolved: TypedContractEvent<
      PredictionResolvedEvent.InputTuple,
      PredictionResolvedEvent.OutputTuple,
      PredictionResolvedEvent.OutputObject
    >;
  };
}
