/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace StrategyRegistry {
  export type FollowerStruct = {
    user: AddressLike;
    amountInvested: BigNumberish;
    shares: BigNumberish;
    joinedAt: BigNumberish;
  };

  export type FollowerStructOutput = [
    user: string,
    amountInvested: bigint,
    shares: bigint,
    joinedAt: bigint
  ] & {
    user: string;
    amountInvested: bigint;
    shares: bigint;
    joinedAt: bigint;
  };
}

export interface StrategyRegistryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "MAX_FEE_BPS"
      | "createStrategy"
      | "followStrategy"
      | "getStrategyFollowers"
      | "getTopStrategies"
      | "getUserFollowedStrategies"
      | "getUserStrategies"
      | "isFollowing"
      | "owner"
      | "renounceOwnership"
      | "strategies"
      | "strategyFollowers"
      | "strategyIdCounter"
      | "transferOwnership"
      | "unfollowStrategy"
      | "updateGains"
      | "userFollowedStrategies"
      | "userStrategies"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "GainsUpdated"
      | "OwnershipTransferred"
      | "StrategyCreated"
      | "StrategyFollowed"
      | "StrategyUnfollowed"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "MAX_FEE_BPS",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "createStrategy",
    values: [string, string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "followStrategy",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getStrategyFollowers",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getTopStrategies",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getUserFollowedStrategies",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getUserStrategies",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isFollowing",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "strategies",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "strategyFollowers",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "strategyIdCounter",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "unfollowStrategy",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "updateGains",
    values: [BigNumberish, BigNumberish, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "userFollowedStrategies",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "userStrategies",
    values: [AddressLike, BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "MAX_FEE_BPS",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createStrategy",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "followStrategy",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getStrategyFollowers",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTopStrategies",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getUserFollowedStrategies",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getUserStrategies",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isFollowing",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "strategies", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "strategyFollowers",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "strategyIdCounter",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "unfollowStrategy",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateGains",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "userFollowedStrategies",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "userStrategies",
    data: BytesLike
  ): Result;
}

export namespace GainsUpdatedEvent {
  export type InputTuple = [
    strategyId: BigNumberish,
    totalGains: BigNumberish,
    todayGains: BigNumberish
  ];
  export type OutputTuple = [
    strategyId: bigint,
    totalGains: bigint,
    todayGains: bigint
  ];
  export interface OutputObject {
    strategyId: bigint;
    totalGains: bigint;
    todayGains: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace StrategyCreatedEvent {
  export type InputTuple = [
    strategyId: BigNumberish,
    creator: AddressLike,
    name: string,
    feeBPS: BigNumberish
  ];
  export type OutputTuple = [
    strategyId: bigint,
    creator: string,
    name: string,
    feeBPS: bigint
  ];
  export interface OutputObject {
    strategyId: bigint;
    creator: string;
    name: string;
    feeBPS: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace StrategyFollowedEvent {
  export type InputTuple = [
    strategyId: BigNumberish,
    follower: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [
    strategyId: bigint,
    follower: string,
    amount: bigint
  ];
  export interface OutputObject {
    strategyId: bigint;
    follower: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace StrategyUnfollowedEvent {
  export type InputTuple = [strategyId: BigNumberish, follower: AddressLike];
  export type OutputTuple = [strategyId: bigint, follower: string];
  export interface OutputObject {
    strategyId: bigint;
    follower: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface StrategyRegistry extends BaseContract {
  connect(runner?: ContractRunner | null): StrategyRegistry;
  waitForDeployment(): Promise<this>;

  interface: StrategyRegistryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  MAX_FEE_BPS: TypedContractMethod<[], [bigint], "view">;

  createStrategy: TypedContractMethod<
    [name: string, description: string, feeBPS: BigNumberish],
    [bigint],
    "nonpayable"
  >;

  followStrategy: TypedContractMethod<
    [strategyId: BigNumberish],
    [void],
    "payable"
  >;

  getStrategyFollowers: TypedContractMethod<
    [strategyId: BigNumberish],
    [StrategyRegistry.FollowerStructOutput[]],
    "view"
  >;

  getTopStrategies: TypedContractMethod<
    [limit: BigNumberish],
    [[bigint[], bigint[]]],
    "view"
  >;

  getUserFollowedStrategies: TypedContractMethod<
    [user: AddressLike],
    [bigint[]],
    "view"
  >;

  getUserStrategies: TypedContractMethod<
    [user: AddressLike],
    [bigint[]],
    "view"
  >;

  isFollowing: TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [boolean],
    "view"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  strategies: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        bigint,
        string,
        string,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        boolean,
        bigint
      ] & {
        id: bigint;
        creator: string;
        name: string;
        description: string;
        feeBPS: bigint;
        totalFollowers: bigint;
        totalValueLocked: bigint;
        totalGains: bigint;
        todayGains: bigint;
        active: boolean;
        createdAt: bigint;
      }
    ],
    "view"
  >;

  strategyFollowers: TypedContractMethod<
    [arg0: BigNumberish, arg1: BigNumberish],
    [
      [string, bigint, bigint, bigint] & {
        user: string;
        amountInvested: bigint;
        shares: bigint;
        joinedAt: bigint;
      }
    ],
    "view"
  >;

  strategyIdCounter: TypedContractMethod<[], [bigint], "view">;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  unfollowStrategy: TypedContractMethod<
    [strategyId: BigNumberish],
    [void],
    "nonpayable"
  >;

  updateGains: TypedContractMethod<
    [strategyId: BigNumberish, gains: BigNumberish, isToday: boolean],
    [void],
    "nonpayable"
  >;

  userFollowedStrategies: TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [bigint],
    "view"
  >;

  userStrategies: TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [bigint],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "MAX_FEE_BPS"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "createStrategy"
  ): TypedContractMethod<
    [name: string, description: string, feeBPS: BigNumberish],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "followStrategy"
  ): TypedContractMethod<[strategyId: BigNumberish], [void], "payable">;
  getFunction(
    nameOrSignature: "getStrategyFollowers"
  ): TypedContractMethod<
    [strategyId: BigNumberish],
    [StrategyRegistry.FollowerStructOutput[]],
    "view"
  >;
  getFunction(
    nameOrSignature: "getTopStrategies"
  ): TypedContractMethod<[limit: BigNumberish], [[bigint[], bigint[]]], "view">;
  getFunction(
    nameOrSignature: "getUserFollowedStrategies"
  ): TypedContractMethod<[user: AddressLike], [bigint[]], "view">;
  getFunction(
    nameOrSignature: "getUserStrategies"
  ): TypedContractMethod<[user: AddressLike], [bigint[]], "view">;
  getFunction(
    nameOrSignature: "isFollowing"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "strategies"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        bigint,
        string,
        string,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        boolean,
        bigint
      ] & {
        id: bigint;
        creator: string;
        name: string;
        description: string;
        feeBPS: bigint;
        totalFollowers: bigint;
        totalValueLocked: bigint;
        totalGains: bigint;
        todayGains: bigint;
        active: boolean;
        createdAt: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "strategyFollowers"
  ): TypedContractMethod<
    [arg0: BigNumberish, arg1: BigNumberish],
    [
      [string, bigint, bigint, bigint] & {
        user: string;
        amountInvested: bigint;
        shares: bigint;
        joinedAt: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "strategyIdCounter"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "unfollowStrategy"
  ): TypedContractMethod<[strategyId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "updateGains"
  ): TypedContractMethod<
    [strategyId: BigNumberish, gains: BigNumberish, isToday: boolean],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "userFollowedStrategies"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "userStrategies"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [bigint],
    "view"
  >;

  getEvent(
    key: "GainsUpdated"
  ): TypedContractEvent<
    GainsUpdatedEvent.InputTuple,
    GainsUpdatedEvent.OutputTuple,
    GainsUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "StrategyCreated"
  ): TypedContractEvent<
    StrategyCreatedEvent.InputTuple,
    StrategyCreatedEvent.OutputTuple,
    StrategyCreatedEvent.OutputObject
  >;
  getEvent(
    key: "StrategyFollowed"
  ): TypedContractEvent<
    StrategyFollowedEvent.InputTuple,
    StrategyFollowedEvent.OutputTuple,
    StrategyFollowedEvent.OutputObject
  >;
  getEvent(
    key: "StrategyUnfollowed"
  ): TypedContractEvent<
    StrategyUnfollowedEvent.InputTuple,
    StrategyUnfollowedEvent.OutputTuple,
    StrategyUnfollowedEvent.OutputObject
  >;

  filters: {
    "GainsUpdated(uint256,uint256,uint256)": TypedContractEvent<
      GainsUpdatedEvent.InputTuple,
      GainsUpdatedEvent.OutputTuple,
      GainsUpdatedEvent.OutputObject
    >;
    GainsUpdated: TypedContractEvent<
      GainsUpdatedEvent.InputTuple,
      GainsUpdatedEvent.OutputTuple,
      GainsUpdatedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "StrategyCreated(uint256,address,string,uint256)": TypedContractEvent<
      StrategyCreatedEvent.InputTuple,
      StrategyCreatedEvent.OutputTuple,
      StrategyCreatedEvent.OutputObject
    >;
    StrategyCreated: TypedContractEvent<
      StrategyCreatedEvent.InputTuple,
      StrategyCreatedEvent.OutputTuple,
      StrategyCreatedEvent.OutputObject
    >;

    "StrategyFollowed(uint256,address,uint256)": TypedContractEvent<
      StrategyFollowedEvent.InputTuple,
      StrategyFollowedEvent.OutputTuple,
      StrategyFollowedEvent.OutputObject
    >;
    StrategyFollowed: TypedContractEvent<
      StrategyFollowedEvent.InputTuple,
      StrategyFollowedEvent.OutputTuple,
      StrategyFollowedEvent.OutputObject
    >;

    "StrategyUnfollowed(uint256,address)": TypedContractEvent<
      StrategyUnfollowedEvent.InputTuple,
      StrategyUnfollowedEvent.OutputTuple,
      StrategyUnfollowedEvent.OutputObject
    >;
    StrategyUnfollowed: TypedContractEvent<
      StrategyUnfollowedEvent.InputTuple,
      StrategyUnfollowedEvent.OutputTuple,
      StrategyUnfollowedEvent.OutputObject
    >;
  };
}
